/* empty css                      */import{a as w,S as v,i as l}from"./assets/vendor-D73Uttp0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const E="46842310-1eff6901abe3b896058131b9e",P="https://pixabay.com/api/";async function y(o,t=1){const r=new URLSearchParams({key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});return(await w.get(`${P}?${r}`)).data}function S({webformatURL:o,largeImageURL:t,tags:r,likes:s,views:e,comments:a,downloads:i}){return`
          <li class="gallery-item">
            <a class="gallery-link" href="${t}">
              <img class="gallery-image" src="${o}" alt="${r}" loading="lazy" />
              <div class="image-info">
                <p class="info-item"><b>Likes:</b> ${s}</p>
                <p class="info-item"><b>Views:</b> ${e}</p>
                <p class="info-item"><b>Comments:</b> ${a}</p>
                <p class="info-item"><b>Downloads:</b> ${i}</p>
              </div>
            </a>
          </li>
      `}function L(o,t,r=!1){const s=o.map(S).join("");r?t.insertAdjacentHTML("beforeend",s):t.innerHTML=s}function c(o){const t=document.querySelector(".load-more");t&&(t.style.display=o?"block":"none")}function u(o){const t=document.querySelector(".loader");o?t.classList.add("active"):t.classList.remove("active")}function d(o){const t=document.querySelector(".toast-message");o?(t.classList.add("show"),setTimeout(()=>{t.classList.remove("show")},3e3)):t.classList.remove("show")}let m=1,p="",g=null,h=0,n=0;const f=document.querySelector(".gallery");document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".search-form"),t=document.querySelector(".load-more");g=new v(".gallery a",{captionsData:"alt",captionDelay:250}),o.addEventListener("submit",async r=>{r.preventDefault();const s=r.target.elements.searchQuery.value.trim();if(b(),!s){l.error({title:"Error",message:"Please enter a search query.",position:"topRight",timeout:3e3});return}p=s,m=1,n=0;try{u(!0),c(!1),d(!1);const e=await y(s,m);if(h=e.totalHits,n=e.hits.length,e.hits.length===0){l.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",timeout:3e3});return}L(e.hits,f),g.refresh(),n>=h?d(!0):c(!0)}catch(e){console.error("Error fetching images:",e),l.error({title:"Error",message:"An error occurred while fetching images. Please try again.",position:"topRight",timeout:3e3})}finally{u(!1)}}),t.addEventListener("click",async()=>{m+=1;try{u(!0),c(!1);const r=await y(p,m);n+=r.hits.length,L(r.hits,f,!0),g.refresh();const{height:s}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),n>=h?d(!0):c(!0)}catch(r){console.error("Error fetching more images:",r),l.error({title:"Error",message:"An error occurred while fetching more images. Please try again.",position:"topRight",timeout:3e3}),b()}finally{u(!1)}})});function b(){p="",f.innerHTML=""}
//# sourceMappingURL=index.js.map
